---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: 'Build & Deploy - RELEASE'
on:
  release:
    # Want to run the automation when a release is created
    types: ['created']

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

###############
# Set the Job #
###############
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 22.x
      - name: Setup Dependencies
        run: |
          npm ci
          npm install -g @vscode/vsce ovsx
      - name: Compile VSIX
        run: npm run build
      - name: Publish VSCE Marketplace
        run: vsce publish --pat ${{ secrets.VSCE_PAT }} -i $(ls -all | grep "flow-linter-vsx" | awk '{print $9}')
      - name: Publish OpenVSX Registry
        run: ovsx publish --pat ${{ secrets.OVSX_PAT }} -i $(ls -all | grep "flow-linter-vsx" | awk '{print $9}')
